# Generated by Django 5.0.1 on 2024-01-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_departamentos',
                'ordering': ['departamento'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(db_column='departamento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='select_dinamico.departamento')),
            ],
            options={
                'db_table': 'tbl_municipios',
                'ordering': ['municipio'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(db_column='municipio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='select_dinamico.municipio')),
            ],
            options={
                'db_table': 'tbl_zonas',
                'ordering': ['zona'],
            },
        ),
    ]
